= Architecture characteristics

:toc: macro
:toclevels: 3

toc::[]

:chapter-label:

Published from https://github.com/JakubJablonski2-TomTom/architecture-characteristics.

== External sources

Use below sources as inspiration when searching for the characterictics of your system.

* https://www.iso.org/obp/ui/#iso:std:iso-iec:25010:ed-1:v1:en[ISO/IEC 25010:2011] (chapter 4.2 Product quality model).
* https://learning.oreilly.com/library/view/fundamentals-of-software/9781492043447/ch04.html[Fundamentals of Software Architecture] by By Mark Richards, Neal Ford (chapter 4)

== Characteristics library

'''
=== Accessibility

Does your system need to consider users with a wide range of disabilities?

For example:

* Colorblindness
* Hearing loss
* Disabilities associated with age

*Related characteristics:*

* <<Legal>> - Do you have legal requirements for accessibility in the countries where your system works?
* <<Compliance>> - Do you have rules or regulations that you need to comply with?

'''
=== Adaptability

Does your system need to adapt to:

* different hardware
* different screen sizes
* different operating systems
* different public cloud providers?

Does your system need to adapt automatically, by human operator, by the user?

'''
=== Accountability

'''
=== Availability

How much downtime is acceptable?

99.9% - 10m 4s per week +
99.99% - 4m 22s per month +
99.999% - 5m 15s per year

Can you handle incidents manually or do you need automated way to bring your system back to life?

Does your system depend on other systems, and what is their availability?

What "available" means for the users of your system?

Can you afford to have planned downtime?

Do you have multiple tenants in the system that require different level of availability?

*Related characteristics:*

* <<Legal>> - Do you have legal requirements about availability?
* <<Fault tolerance>> - For high availability you may need the system to be operational even if something fails.
* <<Recoverability>> - For high availability you probably need the system to recover itself after a failure.
* <<Reliability>> - For high availability you usually need high reliability.
* <<Robustness>> - If the system erodes with time, the high availability may be harder and harder to achieve.

*See also*

* https://uptime.is
* https://sre.google/sre-book/service-level-objectives/[Service Level Objectives]
* https://cloud.google.com/blog/products/devops-sre/sre-fundamentals-sli-vs-slo-vs-sla[SRE fundamentals 2021: SLIs vs SLAs vs SLOs]

'''
=== Capacity

How much traffic does your system need to support?
How many users/calls/gigabytes of data?

*Related characteristics:*

* <<Scalability>> - if the capacity of your system needs to grow or shrink, automatically or manually
* <<Elasticity>> - if the capacity of your system needs to grow and shrink rapidly and automatically

'''
=== Co-existence

*Related characteristics:*

* <<Compatibility>>

'''
=== Compatibility

*Related characteristics:*

* <<Interoperability>>
* <<Co-existence>>
* <<Portability>>

'''
=== Compliance

Are there any standards, laws or regulations that you need to follow, either from the industry or from standarization bodies?

*Related characteristics:*

* <<Accessibility>> - Do you have rules or regulations that you need to comply with?
* <<Configurability>> - Do you have rules, regulations or industry standards that you need to comply with?
* <<Legal>>
* <<Security>> - Are there security rules or regulations that you need to comply with?

'''
=== Concurrency

'''
=== Confidentiality

Does your system store or process personal data that only owners should have access to?
Does your system store or process sensitive data that can be used against people if made available for unauthorized parties?

*Related characteristics:*

* <<Legal>> - Are there any legal rules to keep data confidential?
Do you operate your system in Europe and need to follow GDPR, or similar regulations in other places?
* <<Security>> - More general term for <<Confidentiality>>, <<Integrity>> and other related characteristics.
* <<Integrity>> - Does your system need to keep data intact, not only secret?

'''
=== Configurability

Does your system need to be configurable in any way?

Who is expected to configure it:

* final user;
* operator on the client side;
* developers?

Is the configuration done in the runtime, in deployment time, in build time?

If the configuration is changed in runtime, when does it become effective? Immediately, after restart?

*Related characteristics:*

* <<Compliance>> - Are there any configuration standards your system needs to follow? SNMP, CLI, HTTP?

'''
=== Continuity

'''
=== Deployability

'''
=== Durability

*Related characteristics:*

* <<Resilience>>

'''
=== Ease of integration

'''
=== Elasticity

Does the capacity of your system need to grow and shrink rapidly and automatically?
If there is a breaking news related to your domain, do you need to handle the sudden peak in your system?

*Related characteristics:*

* <<Capacity>>
* <<Scalability>>

'''
=== Evolvability

'''
=== Extensibility

'''
=== Fault tolerance

*Related characteristics:*

* <<Availability>>

'''
=== Feasibility

'''
=== Integrity

Does your system need to keep the data intact, so that user know it's genuine and hasn't been tampered with?

*Related characteristics:*

* <<Confidentiality>> - Do you need to keep the data secret, or maybe only intact?

'''
=== Interoperability

*Related characteristics:*

* <<Compatibility>>

'''
=== Latency

'''
=== Legal

*Related characteristics:*

* <<Accessibility>> - Do you have legal requirements for accessibility in the countries where your system works?
* <<Availability>>
* <<Compliance>>
* <<Confidentiality>>

'''
=== Localization

'''
=== Modifiability

'''
=== Non-repudiation

*Related characteristics:*

* <<Repudiation>>

'''
=== Performance

'''
=== Portability

*Related characteristics:*

* <<Compatibility>>

'''
=== Privacy

'''
=== Recoverability

*Related characteristics:*

* <<Availability>>

'''
=== Reliability

*Related characteristics:*

* <<Availability>>

*See also:*

* https://www.engadget.com/2015-05-01-boeing-787-dreamliner-software-bug.html[To keep a Boeing Dreamliner flying, reboot once every 248 days]

'''
=== Repudiation

*Related characteristics:*

* <<Non-repudiation>>

'''
=== Resilience

*Related characteristics:*

* <<Durability>>

'''
=== Robustness

*Related characteristics:*

* <<Availability>>

'''
=== Safety

Does your system affect people's lives or large amounts of money?
If it fails, can someone be hurt?

*Related characteristics:*

* <<Security>>

'''
=== Scalability

Does your system's capacity need to grow or shrink?
Does it happen periodically in time, daily, weekly, monthly, yearly?
Does it happen randomly in unpredictable moments?

*Related characteristics:*

* <<Capacity>> - Scalability is usually defined in terms of changes in system's capacity.
* <<Elasticity>> - If the amount of scaling is huge and unpredictable, maybe you need elasticity.

'''
=== Security

Should the access to your system be limited to authorized users?
Does your system need to protect the data at rest and in transit?
Can your system rely on external systems to protect the data on its behalf?

*Related characteristics:*

* <<Compliance>> - Are there any security standards your system needs to meet?
* <<Confidentiality>> - Part of Security.
* <<Safety>>

'''
=== Testability



'''
=== Throughput

'''
=== Usability
